project_name: alaala

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: alaala
    main: ./cmd/alaala
    binary: alaala
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: alaala
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - QUICKSTART.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Enhancements'
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

brews:
  - name: alaala
    repository:
      owner: 0xGurg
      name: homebrew-alaala
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/0xGurg/alaala"
    description: "ᜀᜎᜀᜎ - Semantic memory system for AI assistants"
    license: "MIT"
    skip_upload: false
    dependencies:
      - name: docker
        type: recommended
    install: |
      bin.install "alaala"
    post_install: |
      ohai "ᜀᜎᜀᜎ (alaala) installed successfully!"
      puts ""
      puts "Setup Weaviate for vector search:"
      puts "  docker run -d --name weaviate -p 8080:8080 \\"
      puts "    -e AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true \\"
      puts "    -e PERSISTENCE_DATA_PATH=/var/lib/weaviate \\"
      puts "    weaviate/weaviate:latest"
      puts ""
      puts "Quick start:"
      puts "  1. Get OpenRouter API key: https://openrouter.ai (free tier available)"
      puts "  2. alaala init"
      puts "  3. Configure for Cursor - see README"
    test: |
      assert_match "alaala version", shell_output("#{bin}/alaala version")
    caveats: |
      Weaviate is required for vector search.
      
      Setup with Docker:
        docker run -d --name weaviate -p 8080:8080 \
          -e AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true \
          weaviate/weaviate:latest

release:
  github:
    owner: 0xGurg
    name: alaala
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## ᜀᜎᜀᜎ {{ .Tag }}
    
    Semantic memory system for AI assistants.
  footer: |
    ## Installation
    
    ### Using Homebrew (Recommended)
    
    ```bash
    brew tap 0xGurg/alaala
    brew install alaala
    ```
    
    ### Using Binary
    
    Download the appropriate binary for your platform and extract it:
    
    ```bash
    # macOS (ARM64)
    curl -L https://github.com/0xGurg/alaala/releases/download/{{ .Tag }}/alaala_darwin_arm64.tar.gz | tar xz
    sudo mv alaala /usr/local/bin/
    
    # macOS (AMD64)
    curl -L https://github.com/0xGurg/alaala/releases/download/{{ .Tag }}/alaala_darwin_amd64.tar.gz | tar xz
    sudo mv alaala /usr/local/bin/
    
    # Linux (AMD64)
    curl -L https://github.com/0xGurg/alaala/releases/download/{{ .Tag }}/alaala_linux_amd64.tar.gz | tar xz
    sudo mv alaala /usr/local/bin/
    
    # Linux (ARM64)
    curl -L https://github.com/0xGurg/alaala/releases/download/{{ .Tag }}/alaala_linux_arm64.tar.gz | tar xz
    sudo mv alaala /usr/local/bin/
    ```
    
    Or use the latest release: https://github.com/0xGurg/alaala/releases/latest
    
    ### Verify Checksum
    
    ```bash
    sha256sum -c checksums.txt
    ```
    
    **Full Changelog**: https://github.com/0xGurg/alaala/compare/{{ .PreviousTag }}...{{ .Tag }}

